version: '3.8'
services:
  plumber_r:
    image: plumberdb
    ports:
    - "8080:8080"
    networks:
      - tmp
  plumber_db:
    image: postgres
    ports:
    - "1044:5432"
    networks:
      - tmp
    volumes:
      - "pg_data:/var/lib/postgresql/data"
networks:
  tmp:
volumes:
  pg_data: