name: Build Image
on:
  push:
    branches:
    - main
jobs:
  build_image:
    runs-on: self-hosted
    steps:
    - name: Echo test
      run: |
        echo "Test1"
        echo "Test2"
        docker build -t plumbertest .